package com.moa.domain.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum PushCodeType {
    
    // ===== 커뮤니티 알림 (1개) =====
    INQUIRY_ANSWER("INQUIRY_ANSWER", "COMMUNITY"),
    
    // ===== 파티 알림 (6개) =====
    PARTY_JOIN("PARTY_JOIN", "PARTY"),
    PARTY_WITHDRAW("PARTY_WITHDRAW", "PARTY"),
    PARTY_START("PARTY_START", "PARTY"),
    PARTY_CLOSED("PARTY_CLOSED", "PARTY"),
    PARTY_MEMBER_JOIN("PARTY_MEMBER_JOIN", "PARTY"),
    PARTY_MEMBER_WITHDRAW("PARTY_MEMBER_WITHDRAW", "PARTY"),
    
    // ===== 결제 알림 (10개) =====
    PAY_UPCOMING("PAY_UPCOMING", "PAYMENT"),
    PAY_SUCCESS("PAY_SUCCESS", "PAYMENT"),
    PAY_FAILED_RETRY("PAY_FAILED_RETRY", "PAYMENT"),
    PAY_FAILED_BALANCE("PAY_FAILED_BALANCE", "PAYMENT"),
    PAY_FAILED_LIMIT("PAY_FAILED_LIMIT", "PAYMENT"),
    PAY_FAILED_CARD("PAY_FAILED_CARD", "PAYMENT"),
    PAY_FINAL_FAILED("PAY_FINAL_FAILED", "PAYMENT"),
    PAY_MEMBER_FAILED_LEADER("PAY_MEMBER_FAILED_LEADER", "PAYMENT"),
    PAY_RETRY_SUCCESS("PAY_RETRY_SUCCESS", "PAYMENT"),
    PAY_TIMEOUT("PAY_TIMEOUT", "PAYMENT"),
    
    // ===== 보증금 알림 (3개) =====
    DEPOSIT_REFUNDED("DEPOSIT_REFUNDED", "DEPOSIT"),
    DEPOSIT_FORFEITED("DEPOSIT_FORFEITED", "DEPOSIT"),
    REFUND_SUCCESS("REFUND_SUCCESS", "DEPOSIT"),
    
    // ===== 정산 알림 (3개) =====
    SETTLE_COMPLETED("SETTLE_COMPLETED", "SETTLEMENT"),
    SETTLE_FAILED("SETTLE_FAILED", "SETTLEMENT"),
    ACCOUNT_REQUIRED("ACCOUNT_REQUIRED", "SETTLEMENT"),
    
    // ===== 오픈뱅킹 알림 (4개) =====
    VERIFY_REQUESTED("VERIFY_REQUESTED", "OPENBANKING"),
    ACCOUNT_VERIFIED("ACCOUNT_VERIFIED", "OPENBANKING"),
    VERIFY_EXPIRED("VERIFY_EXPIRED", "OPENBANKING"),
    VERIFY_EXCEEDED("VERIFY_EXCEEDED", "OPENBANKING");
    
    private final String code;
    private final String moduleType;
}