-- ============================================
-- OTT 구독 공유 서비스 MOA 데이터베이스
-- Version: 5.0 (Strict Mode + DATETIME)
-- 작성일: 2025.12.09
-- 특징: 
--   - 외래키 제약조건 ALTER TABLE 분리
--   - DATE → DATETIME 타입 변경
--   - 순환참조 해결 구조
--   - PAYMENT_RETRY_HISTORY 추가 (결제 재시도 이력)
--   - REFUND_RETRY_HISTORY 추가 (환불 재시도 이력)
--   - SETTLEMENT_RETRY_HISTORY 추가 (정산 재시도 이력)
--   - BANK_CODE 추가 (은행 코드 참조)
--   - CHATBOT_KNOWLEDGE 추가 (챗봇 지식 베이스)
--   - USERS.PASSWORD NULL 허용 (소셜 로그인 대응)
-- ============================================

-- ============================================
-- 1. 초기화 (기존 테이블 삭제)
-- ============================================
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS SETTLEMENT_RETRY_HISTORY;
DROP TABLE IF EXISTS REFUND_RETRY_HISTORY;
DROP TABLE IF EXISTS PAYMENT_RETRY_HISTORY;
DROP TABLE IF EXISTS SETTLEMENT_DETAIL;
DROP TABLE IF EXISTS SETTLEMENT;
DROP TABLE IF EXISTS PAYMENT;
DROP TABLE IF EXISTS DEPOSIT;
DROP TABLE IF EXISTS PARTY_MEMBER;
DROP TABLE IF EXISTS PARTY;
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS USER_CARD;
DROP TABLE IF EXISTS SUBSCRIPTION;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS PUSH;
DROP TABLE IF EXISTS PUSH_CODE;
DROP TABLE IF EXISTS CHATBOT_KNOWLEDGE;
DROP TABLE IF EXISTS COMMUNITY;
DROP TABLE IF EXISTS COMMUNITY_CODE;
DROP TABLE IF EXISTS BLACKLIST;
DROP TABLE IF EXISTS OAUTH_ACCOUNT;
DROP TABLE IF EXISTS EMAIL_VERIFICATION;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS BANK_CODE;

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================
-- 2. 테이블 생성 (외래키 제약조건 제외)
-- ============================================

-- --------------------------------------------
-- 2.0 기초 코드 영역
-- --------------------------------------------

-- BANK_CODE: 은행 코드 참조 테이블
CREATE TABLE BANK_CODE (
    BANK_CODE VARCHAR(10) NOT NULL,
    BANK_NAME VARCHAR(50) NOT NULL,
    IS_ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
    
    PRIMARY KEY (BANK_CODE)
) COMMENT='은행 코드 참조 테이블 (오픈뱅킹 기준)';

-- --------------------------------------------
-- 2.1 회원 영역
-- --------------------------------------------

-- USERS: 회원 정보
CREATE TABLE USERS (
    USER_ID VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(255) NULL,
    NICKNAME VARCHAR(20) NOT NULL,
    PHONE VARCHAR(14) NULL,
    PROFILE_IMAGE VARCHAR(255) NULL,
    ROLE VARCHAR(20) NOT NULL DEFAULT 'USER',
    USER_STATUS VARCHAR(20) NOT NULL,
    
    REG_DATE DATETIME NOT NULL,
    CI VARCHAR(100) NULL,
    PASS_CERTIFIED_AT DATETIME NULL,
    LAST_LOGIN_DATE DATETIME NULL,
    LOGIN_FAIL_COUNT INT NULL DEFAULT 0,
    UNLOCK_SCHEDULED_AT DATETIME NULL,
    DELETE_DATE DATETIME NULL,
    DELETE_TYPE VARCHAR(20) NULL,
    DELETE_DETAIL VARCHAR(500) NULL,
    
    AGREE_MARKETING BOOLEAN NOT NULL DEFAULT 0,
    EMAIL_VERIFICATION_TOKEN VARCHAR(200) NULL,
    EMAIL_VERIFIED_AT DATETIME NULL,
    RESET_TOKEN VARCHAR(200) NULL,
    
    PRIMARY KEY (USER_ID),
    UNIQUE KEY UQ_USERS_CI (CI),
    CONSTRAINT UK_USERS_USER_ID UNIQUE (USER_ID)
) COMMENT='회원 정보 (소셜 로그인 대응: PASSWORD NULL 허용)';

-- OAUTH_ACCOUNT: 소셜 로그인 연동 정보
CREATE TABLE OAUTH_ACCOUNT (
    OAUTH_ID VARCHAR(255) NOT NULL,
    PROVIDER VARCHAR(20) NOT NULL,
    PROVIDER_USER_ID VARCHAR(50) NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    
    CONNECTED_DATE DATETIME NOT NULL,
    RELEASE_DATE DATETIME NULL,
    
    PRIMARY KEY (OAUTH_ID),
    CONSTRAINT UQ_OAUTH_PROVIDER_USER UNIQUE (PROVIDER, PROVIDER_USER_ID),
    CONSTRAINT UQ_OAUTH_USER_PROVIDER UNIQUE (USER_ID, PROVIDER)
) COMMENT='소셜 로그인 연동 정보 (KAKAO, GOOGLE)';

-- BLACKLIST: 블랙리스트 관리
CREATE TABLE BLACKLIST (
    BLACKLIST_ID INT NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(50) NOT NULL,
    REASON VARCHAR(500) NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    REG_DATE DATE NOT NULL,
    RELEASE_DATE DATE NULL,
    
    ACTIVE_USER_ID VARCHAR(50) GENERATED ALWAYS AS (
        CASE WHEN STATUS = 'ACTIVE' THEN USER_ID ELSE NULL END
    ) VIRTUAL,
    
    PRIMARY KEY (BLACKLIST_ID),
    CONSTRAINT UQ_BLACKLIST_ACTIVE_USER UNIQUE (ACTIVE_USER_ID)
) COMMENT='블랙리스트 관리 (ACTIVE 상태만 UNIQUE 보장)';

-- EMAIL_VERIFICATION: 이메일 인증 토큰 관리
CREATE TABLE EMAIL_VERIFICATION (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(50) NOT NULL,
    TOKEN VARCHAR(100) NOT NULL,
    EXPIRES_AT DATETIME NOT NULL,
    VERIFIED_AT DATETIME NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT NOW(),
    
    PRIMARY KEY (ID),
    UNIQUE KEY UQ_EMAIL_VERIFICATION_TOKEN (TOKEN),
    KEY IDX_EMAIL_VERIFICATION_USER (USER_ID)
) COMMENT='이메일 인증 토큰 관리';

-- --------------------------------------------
-- 2.2 게시판 영역
-- --------------------------------------------

-- COMMUNITY_CODE: 커뮤니티 카테고리 코드
CREATE TABLE COMMUNITY_CODE (
    COMMUNITY_CODE_ID INT NOT NULL,
    CATEGORY VARCHAR(20) NOT NULL,
    CODE_NAME VARCHAR(50) NOT NULL,
    
    PRIMARY KEY (COMMUNITY_CODE_ID)
) COMMENT='커뮤니티 카테고리 코드 (INQUIRY/POST)';

-- CHATBOT_KNOWLEDGE: 챗봇 지식 베이스
CREATE TABLE CHATBOT_KNOWLEDGE (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CATEGORY VARCHAR(50) NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    QUESTION TEXT NOT NULL,
    ANSWER TEXT NOT NULL,
    KEYWORDS VARCHAR(500) NULL,
    EMBEDDING JSON NULL COMMENT 'OpenAI 임베딩 벡터 (1536차원)',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    
    PRIMARY KEY (ID),
    INDEX IDX_CHATBOT_KNOWLEDGE_CATEGORY (CATEGORY)
) COMMENT='챗봇 지식 베이스 (FAQ 및 자동 답변용)';

-- COMMUNITY: 게시글 (공지사항, FAQ, 문의)
CREATE TABLE COMMUNITY (
    COMMUNITY_ID INT NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(50) NOT NULL,
    COMMUNITY_CODE_ID INT NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    CONTENT VARCHAR(500) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VIEW_COUNT INT NULL DEFAULT 0,
    FILE_ORIGINAL VARCHAR(255) NULL,
    FILE_UUID VARCHAR(255) NULL,
    ANSWER_CONTENT VARCHAR(500) NULL,
    ANSWERED_AT DATETIME NULL,
    ANSWER_STATUS VARCHAR(20) NULL,
    
    PRIMARY KEY (COMMUNITY_ID)
) COMMENT='게시글 (공지사항/FAQ/문의)';

-- PUSH_CODE: 푸시 알림 템플릿
CREATE TABLE PUSH_CODE (
    PUSH_CODE_ID INT NOT NULL AUTO_INCREMENT,
    CODE_NAME VARCHAR(50) NOT NULL,
    TITLE_TEMPLATE VARCHAR(200) NOT NULL,
    CONTENT_TEMPLATE VARCHAR(500) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (PUSH_CODE_ID)
) COMMENT='푸시 알림 템플릿 (파라미터 치환 지원)';

-- PUSH: 푸시 알림 발송 이력
CREATE TABLE PUSH (
    PUSH_ID INT NOT NULL AUTO_INCREMENT,
    RECEIVER_ID VARCHAR(50) NOT NULL,
    PUSH_CODE VARCHAR(30) NOT NULL,
    TITLE VARCHAR(200) NOT NULL,
    CONTENT VARCHAR(500) NOT NULL,
    MODULE_ID VARCHAR(50) NULL,
    MODULE_TYPE VARCHAR(50) NULL,
    SENT_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    READ_AT DATETIME NULL,
    IS_READ CHAR(1) NOT NULL DEFAULT 'N',
    IS_DELETED CHAR(1) NOT NULL DEFAULT 'N',
    
    PRIMARY KEY (PUSH_ID)
) COMMENT='푸시 알림 발송 이력';

-- --------------------------------------------
-- 2.3 상품/구독 영역
-- --------------------------------------------

-- CATEGORY: 상품 카테고리
CREATE TABLE CATEGORY (
    CATEGORY_ID INT NOT NULL AUTO_INCREMENT,
    CATEGORY_NAME VARCHAR(50) NOT NULL,
    
    PRIMARY KEY (CATEGORY_ID)
) COMMENT='상품 카테고리 (AI/MEDIA/EDU/MEMBER)';

-- PRODUCT: 상품 정보
CREATE TABLE PRODUCT (
    PRODUCT_ID INT NOT NULL AUTO_INCREMENT,
    CATEGORY_ID INT NOT NULL,
    PRODUCT_NAME VARCHAR(30) NOT NULL,
    PRODUCT_STATUS VARCHAR(10) NOT NULL DEFAULT 'ACTIVE',
    PRICE INT NOT NULL,
    IMAGE VARCHAR(255) NULL,
    
    PRIMARY KEY (PRODUCT_ID)
) COMMENT='상품 정보 (OTT 구독 서비스)';

-- SUBSCRIPTION: 구독 정보
CREATE TABLE SUBSCRIPTION (
    SUBSCRIPTION_ID INT NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(50) NOT NULL,
    PRODUCT_ID INT NOT NULL,
    SUBSCRIPTION_STATUS VARCHAR(20) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NULL,
    CANCEL_REASON VARCHAR(255) NULL,
    CANCEL_DATE DATE NULL,
    
    PRIMARY KEY (SUBSCRIPTION_ID)
) COMMENT='구독 정보';

-- --------------------------------------------
-- 2.4 계좌/카드 영역
-- --------------------------------------------

-- ACCOUNT: 정산 계좌 정보
CREATE TABLE ACCOUNT (
    ACCOUNT_ID INT NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(50) NOT NULL,
    BANK_CODE VARCHAR(10) NOT NULL,
    BANK_NAME VARCHAR(50) NOT NULL,
    ACCOUNT_NUMBER VARCHAR(255) NOT NULL,
    ACCOUNT_HOLDER VARCHAR(50) NOT NULL,
    IS_VERIFIED CHAR(1) NOT NULL DEFAULT 'N',
    REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    VERIFY_DATE DATETIME NULL,
    
    PRIMARY KEY (ACCOUNT_ID),
    UNIQUE KEY UQ_ACCOUNT_USER (USER_ID)
) COMMENT='정산 계좌 정보 (파티장 정산용)';

-- USER_CARD: 사용자 카드 정보
CREATE TABLE USER_CARD (
    USER_ID VARCHAR(50) NOT NULL,
    BILLING_KEY VARCHAR(255) NOT NULL,
    CARD_COMPANY VARCHAR(50) NOT NULL,
    CARD_NUMBER VARCHAR(20) NOT NULL,
    REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (USER_ID)
) COMMENT='사용자 카드 정보 (자동결제용 빌링키)';

-- --------------------------------------------
-- 2.5 파티 영역
-- --------------------------------------------

-- PARTY: 파티 정보
CREATE TABLE PARTY (
    PARTY_ID INT NOT NULL AUTO_INCREMENT,
    PRODUCT_ID INT NOT NULL,
    PARTY_LEADER_ID VARCHAR(50) NOT NULL,
    PARTY_STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING_PAYMENT',
    MAX_MEMBERS INT NOT NULL,
    CURRENT_MEMBERS INT NOT NULL DEFAULT 1,
    MONTHLY_FEE INT NOT NULL,
    OTT_ID VARCHAR(100) NULL,
    OTT_PASSWORD VARCHAR(255) NULL,
    ACCOUNT_ID INT NULL,
    REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME NULL,
    LEADER_DEPOSIT_ID INT NULL,
    
    PRIMARY KEY (PARTY_ID)
) COMMENT='파티 정보';

-- PARTY_MEMBER: 파티 멤버 정보
CREATE TABLE PARTY_MEMBER (
    PARTY_MEMBER_ID INT NOT NULL AUTO_INCREMENT,
    PARTY_ID INT NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    MEMBER_ROLE VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
    MEMBER_STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING_PAYMENT',
    JOIN_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    WITHDRAW_DATE DATETIME NULL,
    DEPOSIT_ID INT NULL,
    FIRST_PAYMENT_ID INT NULL,
    
    PRIMARY KEY (PARTY_MEMBER_ID),
    CONSTRAINT UQ_PARTY_MEMBER_USER UNIQUE (PARTY_ID, USER_ID)
) COMMENT='파티 멤버 정보';

-- --------------------------------------------
-- 2.6 결제/보증금 영역
-- --------------------------------------------

-- DEPOSIT: 보증금 정보
CREATE TABLE DEPOSIT (
    DEPOSIT_ID INT NOT NULL AUTO_INCREMENT,
    PARTY_ID INT NOT NULL,
    PARTY_MEMBER_ID INT NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    DEPOSIT_TYPE VARCHAR(20) NOT NULL DEFAULT 'SECURITY',
    DEPOSIT_AMOUNT INT NOT NULL,
    DEPOSIT_STATUS VARCHAR(20) NOT NULL DEFAULT 'PAID',
    PAYMENT_DATE DATETIME NOT NULL,
    REFUND_DATE DATETIME NULL,
    REFUND_AMOUNT INT NULL,
    TRANSACTION_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TOSS_PAYMENT_KEY VARCHAR(255) NULL,
    ORDER_ID VARCHAR(100) NULL,
    
    PRIMARY KEY (DEPOSIT_ID)
) COMMENT='보증금 정보 (LEADER/SECURITY 타입)';

-- PAYMENT: 월회비 결제 정보
CREATE TABLE PAYMENT (
    PAYMENT_ID INT NOT NULL AUTO_INCREMENT,
    PARTY_ID INT NOT NULL,
    PARTY_MEMBER_ID INT NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    PAYMENT_TYPE VARCHAR(20) NOT NULL DEFAULT 'MONTHLY',
    PAYMENT_AMOUNT INT NOT NULL,
    PAYMENT_STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    PAYMENT_METHOD VARCHAR(20) NOT NULL DEFAULT 'CARD',
    PAYMENT_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TOSS_PAYMENT_KEY VARCHAR(255) NULL,
    ORDER_ID VARCHAR(100) NULL,
    CARD_NUMBER VARCHAR(20) NULL,
    CARD_COMPANY VARCHAR(50) NULL,
    TARGET_MONTH VARCHAR(7) NOT NULL,
    
    PRIMARY KEY (PAYMENT_ID),
    CONSTRAINT UQ_PAYMENT_MEMBER_MONTH UNIQUE (PARTY_MEMBER_ID, TARGET_MONTH)
) COMMENT='월회비 결제 정보';

-- PAYMENT_RETRY_HISTORY: 결제 재시도 이력
CREATE TABLE PAYMENT_RETRY_HISTORY (
    RETRY_ID INT PRIMARY KEY AUTO_INCREMENT,
    PAYMENT_ID INT NOT NULL,
    PARTY_ID INT NOT NULL,
    PARTY_MEMBER_ID INT NOT NULL,
    ATTEMPT_NUMBER INT NOT NULL COMMENT '시도 횟수 (1=초기, 2~4=재시도)',
    ATTEMPT_DATE DATETIME NOT NULL COMMENT '시도 일시',
    RETRY_REASON VARCHAR(500) COMMENT '재시도 사유 (이전 시도 에러 메시지)',
    RETRY_STATUS VARCHAR(20) NOT NULL COMMENT '결과 상태 (SUCCESS/FAILED)',
    NEXT_RETRY_DATE DATETIME COMMENT '다음 재시도 예정 일시 (성공 시 NULL)',
    ERROR_CODE VARCHAR(50) COMMENT '토스페이먼츠 에러 코드',
    ERROR_MESSAGE VARCHAR(500) COMMENT '토스페이먼츠 에러 메시지',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT FK_RETRY_PAYMENT FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT(PAYMENT_ID) ON DELETE CASCADE,
    CONSTRAINT FK_RETRY_PARTY FOREIGN KEY (PARTY_ID) REFERENCES PARTY(PARTY_ID) ON DELETE CASCADE,
    CONSTRAINT FK_RETRY_MEMBER FOREIGN KEY (PARTY_MEMBER_ID) REFERENCES PARTY_MEMBER(PARTY_MEMBER_ID) ON DELETE CASCADE,

    INDEX IDX_NEXT_RETRY (NEXT_RETRY_DATE, RETRY_STATUS),
    INDEX IDX_PAYMENT_ATTEMPTS (PAYMENT_ID, ATTEMPT_NUMBER)
) COMMENT='결제 재시도 이력 (자동결제 실패 시 최대 4회 시도 추적)';

-- --------------------------------------------
-- 2.7 정산 영역
-- --------------------------------------------

-- SETTLEMENT: 정산 정보
CREATE TABLE SETTLEMENT (
    SETTLEMENT_ID INT NOT NULL AUTO_INCREMENT,
    PARTY_ID INT NOT NULL,
    PARTY_LEADER_ID VARCHAR(50) NOT NULL,
    ACCOUNT_ID INT NULL,
    SETTLEMENT_MONTH VARCHAR(7) NOT NULL,
    SETTLEMENT_TYPE VARCHAR(20) NOT NULL DEFAULT 'MONTHLY',
    TOTAL_AMOUNT INT NOT NULL,
    COMMISSION_RATE DECIMAL(3,2) NOT NULL DEFAULT 0.15,
    COMMISSION_AMOUNT INT NOT NULL,
    NET_AMOUNT INT NOT NULL,
    SETTLEMENT_STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    SETTLEMENT_DATE DATETIME NULL,
    REG_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    BANK_TRAN_ID VARCHAR(20) NULL COMMENT '오픈뱅킹 거래고유번호',
    
    PRIMARY KEY (SETTLEMENT_ID),
    CONSTRAINT CHK_SETTLEMENT_STATUS CHECK (SETTLEMENT_STATUS IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED'))
) COMMENT='정산 정보 (파티장 월간 정산)';

-- REFUND_RETRY_HISTORY: 환불 재시도 이력
CREATE TABLE REFUND_RETRY_HISTORY (
    RETRY_ID INT NOT NULL AUTO_INCREMENT,
    DEPOSIT_ID INT NOT NULL,
    ATTEMPT_NUMBER INT NOT NULL DEFAULT 1 COMMENT '시도 횟수 (1=초기, 2~4=재시도)',
    ATTEMPT_DATE DATETIME NOT NULL COMMENT '시도 일시',
    RETRY_STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDING' COMMENT '결과 상태 (PENDING/SUCCESS/FAILED)',
    NEXT_RETRY_DATE DATETIME NULL COMMENT '다음 재시도 예정 일시',
    REFUND_AMOUNT INT NULL COMMENT '환불 금액',
    REFUND_REASON VARCHAR(200) NULL COMMENT '환불 사유',
    ERROR_CODE VARCHAR(50) NULL COMMENT '토스페이먼츠 에러 코드',
    ERROR_MESSAGE VARCHAR(500) NULL COMMENT '토스페이먼츠 에러 메시지',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,
    
    PRIMARY KEY (RETRY_ID),
    INDEX IDX_REFUND_RETRY_DEPOSIT (DEPOSIT_ID),
    INDEX IDX_REFUND_RETRY_STATUS (RETRY_STATUS)
) COMMENT='환불 재시도 이력 (보증금 환불 실패 시 최대 4회 시도 추적)';

-- SETTLEMENT_RETRY_HISTORY: 정산 재시도 이력
CREATE TABLE SETTLEMENT_RETRY_HISTORY (
    RETRY_ID INT NOT NULL AUTO_INCREMENT,
    SETTLEMENT_ID INT NOT NULL,
    PARTY_ID INT NOT NULL,
    PARTY_LEADER_ID VARCHAR(50) NOT NULL,
    ACCOUNT_ID INT NULL,
    ATTEMPT_NUMBER INT NOT NULL COMMENT '시도 횟수 (1=초기, 2~4=재시도)',
    ATTEMPT_DATE DATETIME NOT NULL COMMENT '시도 일시',
    RETRY_REASON VARCHAR(500) NULL COMMENT '재시도 사유',
    RETRY_STATUS VARCHAR(20) NOT NULL COMMENT '결과 상태 (SUCCESS/FAILED)',
    NEXT_RETRY_DATE DATETIME NULL COMMENT '다음 재시도 예정 일시',
    TRANSFER_AMOUNT INT NOT NULL COMMENT '이체 금액',
    ERROR_CODE VARCHAR(50) NULL COMMENT '오픈뱅킹 에러 코드',
    ERROR_MESSAGE VARCHAR(500) NULL COMMENT '오픈뱅킹 에러 메시지',
    BANK_RSP_CODE VARCHAR(10) NULL COMMENT '은행 응답 코드',
    BANK_RSP_MESSAGE VARCHAR(200) NULL COMMENT '은행 응답 메시지',
    BANK_TRAN_ID VARCHAR(30) NULL COMMENT '오픈뱅킹 거래고유번호',
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (RETRY_ID),
    INDEX IDX_SETTLEMENT_RETRY_STATUS (RETRY_STATUS),
    INDEX IDX_SETTLEMENT_RETRY_NEXT (NEXT_RETRY_DATE, RETRY_STATUS)
) COMMENT='정산 재시도 이력 (오픈뱅킹 이체 실패 시 최대 4회 시도 추적)';

-- ============================================
-- 3. 외래키 제약조건 추가 (ALTER TABLE)
-- ============================================

-- --------------------------------------------
-- 3.1 회원 영역 외래키
-- --------------------------------------------

ALTER TABLE OAUTH_ACCOUNT 
    ADD CONSTRAINT FK_OAUTH_USER 
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE BLACKLIST 
    ADD CONSTRAINT FK_BLACKLIST_USER 
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE EMAIL_VERIFICATION 
    ADD CONSTRAINT FK_EMAIL_VERIFICATION_USER 
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) 
    ON DELETE CASCADE;

-- --------------------------------------------
-- 3.2 게시판 영역 외래키
-- --------------------------------------------

ALTER TABLE COMMUNITY 
    ADD CONSTRAINT FK_COMMUNITY_USER 
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE COMMUNITY 
    ADD CONSTRAINT FK_COMMUNITY_CODE 
    FOREIGN KEY (COMMUNITY_CODE_ID) REFERENCES COMMUNITY_CODE(COMMUNITY_CODE_ID);

ALTER TABLE PUSH 
    ADD CONSTRAINT FK_PUSH_RECEIVER 
    FOREIGN KEY (RECEIVER_ID) REFERENCES USERS(USER_ID);

-- --------------------------------------------
-- 3.3 상품/구독 영역 외래키
-- --------------------------------------------

ALTER TABLE PRODUCT 
    ADD CONSTRAINT FK_PRODUCT_CATEGORY 
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID);

ALTER TABLE SUBSCRIPTION 
    ADD CONSTRAINT FK_SUBS_USER 
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE SUBSCRIPTION 
    ADD CONSTRAINT FK_SUBS_PRODUCT 
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID);

-- --------------------------------------------
-- 3.4 계좌/카드 영역 외래키
-- --------------------------------------------

ALTER TABLE ACCOUNT 
    ADD CONSTRAINT FK_ACCOUNT_USER 
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE USER_CARD 
    ADD CONSTRAINT FK_CARD_USER 
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

-- --------------------------------------------
-- 3.5 파티 영역 외래키
-- --------------------------------------------

ALTER TABLE PARTY 
    ADD CONSTRAINT FK_PARTY_PRODUCT 
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID);

ALTER TABLE PARTY 
    ADD CONSTRAINT FK_PARTY_LEADER 
    FOREIGN KEY (PARTY_LEADER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE PARTY 
    ADD CONSTRAINT FK_PARTY_ACCOUNT 
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID);

ALTER TABLE PARTY 
    ADD CONSTRAINT FK_PARTY_LEADER_DEPOSIT 
    FOREIGN KEY (LEADER_DEPOSIT_ID) REFERENCES DEPOSIT(DEPOSIT_ID);

ALTER TABLE PARTY_MEMBER 
    ADD CONSTRAINT FK_MEMBER_PARTY 
    FOREIGN KEY (PARTY_ID) REFERENCES PARTY(PARTY_ID);

ALTER TABLE PARTY_MEMBER 
    ADD CONSTRAINT FK_MEMBER_USER 
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE PARTY_MEMBER 
    ADD CONSTRAINT FK_MEMBER_DEPOSIT 
    FOREIGN KEY (DEPOSIT_ID) REFERENCES DEPOSIT(DEPOSIT_ID);

ALTER TABLE PARTY_MEMBER 
    ADD CONSTRAINT FK_MEMBER_PAYMENT 
    FOREIGN KEY (FIRST_PAYMENT_ID) REFERENCES PAYMENT(PAYMENT_ID);

-- --------------------------------------------
-- 3.6 결제/보증금 영역 외래키
-- --------------------------------------------

ALTER TABLE DEPOSIT 
    ADD CONSTRAINT FK_DEPOSIT_PARTY 
    FOREIGN KEY (PARTY_ID) REFERENCES PARTY(PARTY_ID);

ALTER TABLE DEPOSIT 
    ADD CONSTRAINT FK_DEPOSIT_MEMBER 
    FOREIGN KEY (PARTY_MEMBER_ID) REFERENCES PARTY_MEMBER(PARTY_MEMBER_ID);

ALTER TABLE DEPOSIT 
    ADD CONSTRAINT FK_DEPOSIT_USER 
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE PAYMENT 
    ADD CONSTRAINT FK_PAYMENT_PARTY 
    FOREIGN KEY (PARTY_ID) REFERENCES PARTY(PARTY_ID);

ALTER TABLE PAYMENT 
    ADD CONSTRAINT FK_PAYMENT_MEMBER 
    FOREIGN KEY (PARTY_MEMBER_ID) REFERENCES PARTY_MEMBER(PARTY_MEMBER_ID);

ALTER TABLE PAYMENT 
    ADD CONSTRAINT FK_PAYMENT_USER 
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID);

-- --------------------------------------------
-- 3.7 정산 영역 외래키
-- --------------------------------------------

ALTER TABLE SETTLEMENT 
    ADD CONSTRAINT FK_SETTLE_PARTY 
    FOREIGN KEY (PARTY_ID) REFERENCES PARTY(PARTY_ID);

ALTER TABLE SETTLEMENT 
    ADD CONSTRAINT FK_SETTLE_LEADER 
    FOREIGN KEY (PARTY_LEADER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE SETTLEMENT 
    ADD CONSTRAINT FK_SETTLE_ACCOUNT 
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID);

ALTER TABLE REFUND_RETRY_HISTORY
    ADD CONSTRAINT FK_REFUND_RETRY_DEPOSIT
    FOREIGN KEY (DEPOSIT_ID) REFERENCES DEPOSIT(DEPOSIT_ID);

ALTER TABLE SETTLEMENT_RETRY_HISTORY
    ADD CONSTRAINT FK_SETTLE_RETRY_SETTLEMENT
    FOREIGN KEY (SETTLEMENT_ID) REFERENCES SETTLEMENT(SETTLEMENT_ID);

ALTER TABLE SETTLEMENT_RETRY_HISTORY
    ADD CONSTRAINT FK_SETTLE_RETRY_PARTY
    FOREIGN KEY (PARTY_ID) REFERENCES PARTY(PARTY_ID);

ALTER TABLE SETTLEMENT_RETRY_HISTORY
    ADD CONSTRAINT FK_SETTLE_RETRY_LEADER
    FOREIGN KEY (PARTY_LEADER_ID) REFERENCES USERS(USER_ID);

ALTER TABLE SETTLEMENT_RETRY_HISTORY
    ADD CONSTRAINT FK_SETTLE_RETRY_ACCOUNT
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID);

-- ============================================
-- 스키마 생성 완료
-- ============================================